"""
Schemas Pydantic adicionales del microservicio INVEB Envases OT.
Los schemas principales están en los modelos SQLModel.
"""
from .common import (
    parse_decimal_chile,
    format_decimal_chile,
    DecimalChile,
    OptionalDecimalChile,
)

from .cotizacion import (
    CotizacionEstadoBase,
    CotizacionEstadoResponse,
    CotizacionBase,
    CotizacionCreate,
    CotizacionUpdate,
    CotizacionResponse,
    CotizacionListResponse,
    CotizacionConDetalles,
    CotizacionFilters,
    CotizacionApprovalBase,
    CotizacionApprovalCreate,
    CotizacionApprovalResponse,
    SolicitarAprobacionRequest,
    GestionarAprobacionRequest,
    VersionarCotizacionRequest,
    DuplicarCotizacionRequest,
    RetomarCotizacionRequest,
    CotizacionResumen,
    EstadisticasCotizaciones,
)

from .detalle_cotizacion import (
    TipoDetalle,
    DetalleCotizacionBase,
    DetalleCotizacionCreate,
    DetalleCotizacionUpdate,
    DetalleCotizacionResponse,
    DetalleCotizacionConPrecios,
    CostoComponente,
    PreciosCorrugados,
    PreciosEsquineros,
    CalcularDetalleRequest,
    CalcularDetalleResponse,
    MarcarGanadoPerdidoRequest,
    CargaMasivaDetallesRequest,
    CargaMasivaDetallesResponse,
    IndiceComplejidadRequest,
    IndiceComplejidadResponse,
)

__all__ = [
    # Common - Val 17 sprint H2
    "parse_decimal_chile",
    "format_decimal_chile",
    "DecimalChile",
    "OptionalDecimalChile",
    # Cotizacion
    "CotizacionEstadoBase",
    "CotizacionEstadoResponse",
    "CotizacionBase",
    "CotizacionCreate",
    "CotizacionUpdate",
    "CotizacionResponse",
    "CotizacionListResponse",
    "CotizacionConDetalles",
    "CotizacionFilters",
    "CotizacionApprovalBase",
    "CotizacionApprovalCreate",
    "CotizacionApprovalResponse",
    "SolicitarAprobacionRequest",
    "GestionarAprobacionRequest",
    "VersionarCotizacionRequest",
    "DuplicarCotizacionRequest",
    "RetomarCotizacionRequest",
    "CotizacionResumen",
    "EstadisticasCotizaciones",
    # Detalle Cotizacion
    "TipoDetalle",
    "DetalleCotizacionBase",
    "DetalleCotizacionCreate",
    "DetalleCotizacionUpdate",
    "DetalleCotizacionResponse",
    "DetalleCotizacionConPrecios",
    "CostoComponente",
    "PreciosCorrugados",
    "PreciosEsquineros",
    "CalcularDetalleRequest",
    "CalcularDetalleResponse",
    "MarcarGanadoPerdidoRequest",
    "CargaMasivaDetallesRequest",
    "CargaMasivaDetallesResponse",
    "IndiceComplejidadRequest",
    "IndiceComplejidadResponse",
]
